language: node_js
node_js:
- '0.10'
script: gulp coverage
before_install:
- mkdir -p .npm
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate < coverage/lcov.info
notifications:
  slack:
    secure: Bu3OZ0Cdy8eq0IMoLJmadDba8Yyb9ajobKocfp8V7/vfOjpIVXdFrGMqfckkZ22uiWxHCsYEX1ahQ77zTjbO3tNq1CTmSgEAWaqqMVz1iIVNhSoeHRfYDa9r1sKFpJv1KEz+j/8i2phcR5MDE6cGK+byJmjfjcnkP1XoNiupuck=
